=== Mouad-Louhibi/XML-notes/seance1/ex1.dtd
<!ELEMENT etudiants (etudiant*)>
<!ELEMENT etudiant (nom,prenom,notes)>
<!ATTLIST etudiant cne ID #REQUIRED>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT prenom (#PCDATA)>
<!ELEMENT notes (note*)>
<!ELEMENT note (valeur,matiere)>
<!ATTLIST note id ID #REQUIRED>
<!ELEMENT valeur (#PCDATA)>
<!ELEMENT matiere (#PCDATA)>

=== Mouad-Louhibi/XML-notes/seance1/teste.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE etudiants SYSTEM "ex1.dtd">
<etudiants>
    <etudiant cne="cd1234234">
        <nom>4366354</nom>
        <prenom>mehdi</prenom>
        <notes>
            <note id="n1">
                <valeur>10</valeur>
                <matiere>maths</matiere>
            </note>
            <note id="n2">
                <valeur>0</valeur>
                <matiere>francais</matiere>
            </note>
        </notes>
    </etudiant>
</etudiants>
