=== Mouad-Louhibi/XML-notes/seance2/etudiants.xsd
<?xml version="1.1" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="etudiants" type="etudiantsType"> 
        
    </xs:element>
  
    <xs:simpleType name="stringType" >
        <xs:restriction base="xs:string">
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="matiereType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Maths"></xs:enumeration>
            <xs:enumeration value="Physique"></xs:enumeration>
            <xs:enumeration value="Arabe"></xs:enumeration>
            <xs:enumeration value="Francais"></xs:enumeration>
            <xs:enumeration value="Anglais"></xs:enumeration>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="valeurType">
         <xs:restriction base="xs:decimal">
                <xs:minInclusive value="0"></xs:minInclusive>
                <xs:maxInclusive value="20"></xs:maxInclusive>
         </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="noteType">
        <xs:all>
            <xs:element name="valeur" type="valeurType"></xs:element>
            <xs:element name="matiere" type="matiereType"></xs:element>
        </xs:all>
        <xs:attribute name="id" type="xs:ID" use="required"></xs:attribute>
    </xs:complexType>
    <xs:complexType name="notesType">
        <xs:sequence>
            <xs:element name="note" type="noteType" minOccurs="0"
            maxOccurs="unbounded"></xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="etudiantType">
        <xs:all>
            <xs:element name="nom" type="stringType"></xs:element>
            <xs:element name="prenom" type="stringType"></xs:element>
            <xs:element name="notes" type="notesType"></xs:element>
        </xs:all>
        <xs:attribute name="cne" type="cneType"></xs:attribute>
    </xs:complexType>
    <xs:simpleType name="cneType">
        <xs:restriction base="xs:ID">
            <xs:pattern value="[a-zA-Z0-9][0-9]{9}"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="etudiantsType">
        <xs:sequence>
            <xs:element name="etudiant" type="etudiantType" minOccurs="0"
            maxOccurs="unbounded"></xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== Mouad-Louhibi/XML-notes/seance2/etudiants.xml
<?xml version="1.1" encoding="UTF-8"?>
<etudiants
    xmlns:xsi=
    "http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation=
    "etudiants.xsd">
    <etudiant cne="N123232222">
        
        <prenom>mehdi</prenom>
        <nom>4366354</nom>
        <notes>
            <note id="n1">
                <valeur>10</valeur>
                <matiere>Francais</matiere>
            </note>
            <note id="n2">
                <valeur>19</valeur>
                <matiere>Arabe</matiere>
            </note>
        </notes>
    </etudiant>
</etudiants>
